export const GROUP_MESSAGE_EVENT = 'groupMessage'
export const CONTACT_MESSAGE_EVENT = 'contactMessage'
export const NEW_GROUP_MEMBER_EVENT = 'newGroupMember'
export const NOTIFICATION_MESSAGE_EVENT = 'notificationMessage'
export const GET_USER_SOCKET_ID_EVENT = 'userSocketId'
export const A_PARTICIPANT_JOINED_THE_CHAT_EVENT = 'aParticipantJoinedTheChat' 
export const A_PARTICIPANT_UNJOINED_TO_CHAT_EVENT = 'aParticipantUnjoinedToChat' 
export const A_PARTICIPANT_CHANGED_TO_ROLE_EVENT = 'aParticipantChangedToRoleChat'
export const A_PARTICIPANT_DELETED_BY_ADMIN_CHAT_EVENT = 'aParticipantDeletedByAdminToChat'
export const A_ADMIN_HAS_DELETED_YOU_CHAT_EVENT = 'aAdminHasDeletedYouToChat'
export const A_PARTICIPANT_LEFT_THE_GROUP_CHAT_EVENT = 'aParticipantLeftTheGroupChat'
export const AUTH_EVENT = 'auth'

